TestU01 : added SelfTest status output

diff --git a/.github/workflows/reusable_TestU01.yml b/.github/workflows/reusable_TestU01.yml
--- a/.github/workflows/reusable_TestU01.yml
+++ b/.github/workflows/reusable_TestU01.yml
@@ -67,10 +67,8 @@ jobs:
           #  9 tests, 237 assertions, 0 failures
           #  Finished in 0.00003256 seconds (real) 0.00003197 seconds (proc)
           #  Selftest with RFC 7539 test vectors: PASSED.
-          RES=$(cat ${LOGFILE} | grep PASSED || true)
-          echo "*******************"
-          echo "RES = ${RES}"
-          if [ -n ${RES} ]; then echo "__Selftest status__: Pass ✅" >> $GITHUB_STEP_SUMMARY; else echo "__Selftest status__: Fail ❌ " >> $GITHUB_STEP_SUMMARY; fi
+          SELF_RESULT=$(cat ${LOGFILE} | grep PASSED || true)
+          if [ -n "${SELF_RESULT}" ]; then echo "__Selftest status__: Pass ✅" >> $GITHUB_STEP_SUMMARY; else echo "__Selftest status__: Fail ❌ " >> $GITHUB_STEP_SUMMARY; fi
         fi
         pwd
 
