refact PractRand

diff --git a/.github/workflows/reusable_PractRand.yml b/.github/workflows/reusable_PractRand.yml
--- a/.github/workflows/reusable_PractRand.yml
+++ b/.github/workflows/reusable_PractRand.yml
@@ -33,14 +33,14 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v4
 
-    - name: Run PractRand ${{inputs.generator_name}} with ${{inputs.battery_name}}"
+    - name: Run PractRand ${{inputs.generator_name}} with ${{inputs.battery_name}} MAX
       run: |
         sudo apt install g++-12
         git clone https://github.com/planet36/PractRand.git # Fork of PractRand-pre0.95 with many warnings fixed
         cd PractRand
         CXX=g++-12 CXXFLAGS="-std=c++2a -O3" ./configure
         make
-        ./RNG_test ${{inputs.generator_name}} -tlmax 1G | tee ${{env.LOG_FILE}}
+        ./RNG_test ${{inputs.generator_name}} -tlmax ${{inputs.battery_name}} -multithreaded | tee ${{env.LOG_FILE}}
 
         #git clone https://github.com/tylov-fork/PractRand.git # with GNUmakefile to build/Linux/
         #cd PractRand
@@ -70,15 +70,8 @@ jobs:
     - name: Show error status
       working-directory: ./PractRand
       run: |
-        LOGFILE="found.log"
-        touch $LOGFILE
-        cat ${{env.LOG_FILE}} | grep "unusual"  >> $LOGFILE
-        echo "before ERRORS"
-        ERRORS=$(cat $LOGFILE | wc -l)
-        echo "ERRORS = $ERRORS"
-        if [ -s ${LOGFILE} ]; then echo "__Status__: Fail ❌ ( ${ERRORS} )" >> $GITHUB_STEP_SUMMARY; else echo "__Status__: Pass ✅" >> $GITHUB_STEP_SUMMARY; fi
-        ls -la .
-        #if [ $? -eq 0 ]; then echo "__Status__: Pass ✅" >> $GITHUB_STEP_SUMMARY; else echo "__Status__: Fail ❌ ( ${ERRORS} )" >> $GITHUB_STEP_SUMMARY; fi
+        cat ${{env.LOG_FILE}} | grep "unusual"
+        if [ $? -eq 0 ]; then echo "__Status__: Pass ✅" >> $GITHUB_STEP_SUMMARY; else echo "__Status__: Fail ❌ " >> $GITHUB_STEP_SUMMARY; fi
 
     - name: Show Stats and Analysis Report
       working-directory: ./PractRand
