NIST : added Selftest report

diff --git a/.github/workflows/reusable_NIST.yml b/.github/workflows/reusable_NIST.yml
--- a/.github/workflows/reusable_NIST.yml
+++ b/.github/workflows/reusable_NIST.yml
@@ -64,6 +64,16 @@ jobs:
         ERRORS=$(cat $LOGFILE | wc -l)
         if [ -s ${LOGFILE} ]; then echo "__Status__: Fail ❌ ( ${ERRORS} )" >> $GITHUB_STEP_SUMMARY; else echo "__Status__: Pass ✅" >> $GITHUB_STEP_SUMMARY; fi
 
+        cat $DATAFILE | grep -E "9 tests, 237 assertions|Finished in|Selftest with RFC 7539 test vectors" > $LOGFILE || true
+        echo "*******************"
+        cat $LOGFILE
+        echo "*******************"
+        #  9 tests, 237 assertions, 0 failures
+        #  Finished in 0.00003256 seconds (real) 0.00003197 seconds (proc)
+        #  Selftest with RFC 7539 test vectors: PASSED.
+        SELF_RESULT=$(cat ${LOGFILE} | grep PASSED || true)
+        if [ -n "${SELF_RESULT}" ]; then echo "__Selftest status__: Pass ✅" >> $GITHUB_STEP_SUMMARY; else echo "__Selftest status__: Fail ❌ " >> $GITHUB_STEP_SUMMARY; fi
+
     - name: Show Configuration
       run: |
         echo "__Significance Level α__ :" >> $GITHUB_STEP_SUMMARY
