TestU01 : cleaned code

diff --git a/.github/workflows/reusable_TestU01.yml b/.github/workflows/reusable_TestU01.yml
--- a/.github/workflows/reusable_TestU01.yml
+++ b/.github/workflows/reusable_TestU01.yml
@@ -60,15 +60,17 @@ jobs:
           cat ./AKalashnikova${{inputs.generator_name}}.res | grep "All tests were passed" > $LOGFILE || true
           if [ -s ${LOGFILE} ]; then echo "__Status__: Pass ✅" >> $GITHUB_STEP_SUMMARY; else echo "__Status__: Fail ❌ " >> $GITHUB_STEP_SUMMARY; fi
 
-          cat ./AKalashnikova${{inputs.generator_name}}.res | grep -E "9 tests, 237 assertions|Finished in|Selftest with RFC 7539 test vectors" > $LOGFILE || true
-          echo "*******************"
-          cat $LOGFILE
-          echo "*******************"
-          #  9 tests, 237 assertions, 0 failures
-          #  Finished in 0.00003256 seconds (real) 0.00003197 seconds (proc)
-          #  Selftest with RFC 7539 test vectors: PASSED.
-          SELF_RESULT=$(cat ${LOGFILE} | grep PASSED || true)
-          if [ -n "${SELF_RESULT}" ]; then echo "__Selftest status__: Pass ✅" >> $GITHUB_STEP_SUMMARY; else echo "__Selftest status__: Fail ❌ " >> $GITHUB_STEP_SUMMARY; fi
+          if [ ${{inputs.generator_name}} = 'ChaCha20' ]; then
+            cat ./AKalashnikova${{inputs.generator_name}}.res | grep -E "9 tests, 237 assertions|Finished in|Selftest with RFC 7539 test vectors" > $LOGFILE || true
+            echo "*******************"
+            cat $LOGFILE
+            echo "*******************"
+            #  9 tests, 237 assertions, 0 failures
+            #  Finished in 0.00003256 seconds (real) 0.00003197 seconds (proc)
+            #  Selftest with RFC 7539 test vectors: PASSED.
+            SELF_RESULT=$(cat ${LOGFILE} | grep PASSED || true)
+            if [ -n "${SELF_RESULT}" ]; then echo "__Selftest status__: Pass ✅" >> $GITHUB_STEP_SUMMARY; else echo "__Selftest status__: Fail ❌ " >> $GITHUB_STEP_SUMMARY; fi
+          fi
         fi
         pwd
 
