refact PractRand

diff --git a/.github/workflows/reusable_PractRand.yml b/.github/workflows/reusable_PractRand.yml
--- a/.github/workflows/reusable_PractRand.yml
+++ b/.github/workflows/reusable_PractRand.yml
@@ -69,8 +69,8 @@ jobs:
 
     - name: Show error status
       run: |
-        cat ./PractRand/${{env.LOG_FILE}} | grep unusual
-        if [ $? -eq 0 ]; then echo "__Status__: Fail ❌ " >> $GITHUB_STEP_SUMMARY; else echo "__Status__: Pass ✅" >> $GITHUB_STEP_SUMMARY; fi
+        cat ./PractRand/${{env.LOG_FILE}} | grep "unusual" || echo "__Status__: Pass ✅" >> $GITHUB_STEP_SUMMARY
+        if [ $? -eq 0 ]; then echo "__Status__: Fail ❌ " >> $GITHUB_STEP_SUMMARY; fi
 
     - name: Show Stats and Analysis Report
       working-directory: ./PractRand
