refactored TestU01

diff --git a/.github/workflows/reusable_TestU01.yml b/.github/workflows/reusable_TestU01.yml
--- a/.github/workflows/reusable_TestU01.yml
+++ b/.github/workflows/reusable_TestU01.yml
@@ -55,9 +55,12 @@ jobs:
 
     - name: Show error status
       run: |
-        LOGFILE="found.log"
-        cat ./AKalashnikova${{inputs.generator_name}}.res | grep "All tests were passed" || true > $LOGFILE
-        if [ -s ${LOGFILE} ]; then echo "__Status__: Pass ✅" >> $GITHUB_STEP_SUMMARY; else echo "__Status__: Fail ❌ " >> $GITHUB_STEP_SUMMARY; fi
+        if [ ${{inputs.battery_name}} = "SmallCrush" ] || [ ${{inputs.battery_name}} = "Crush" ] || [ ${{inputs.battery_name}} = "BigCrush" ]; then
+          LOGFILE="found.log"
+          cat ./AKalashnikova${{inputs.generator_name}}.res | grep "All tests were passed" || true > $LOGFILE
+          if [ -s ${LOGFILE} ]; then echo "__Status__: Pass ✅" >> $GITHUB_STEP_SUMMARY; else echo "__Status__: Fail ❌ " >> $GITHUB_STEP_SUMMARY; fi
+        fi
+        pwd
 
     - name: Show Stats and Analysis Report
       run: |
