fixed error output

diff --git a/.github/workflows/reusable_TestU01.yml b/.github/workflows/reusable_TestU01.yml
--- a/.github/workflows/reusable_TestU01.yml
+++ b/.github/workflows/reusable_TestU01.yml
@@ -54,8 +54,9 @@ jobs:
 
     - name: Show error status
       run: |
-        cat ./AKalashnikova${{inputs.generator_name}}.res | grep "All tests were passed"
-        if [ $? -eq 0 ]; then echo "__Status__: Pass ✅" >> $GITHUB_STEP_SUMMARY; else echo "__Status__: Fail ❌ " >> $GITHUB_STEP_SUMMARY; fi
+        LOGFILE="found.log"
+        cat ./AKalashnikova${{inputs.generator_name}}.res | grep "All tests were passed" || true > $LOGFILE
+        if [ -s ${LOGFILE} ]; then echo "__Status__: Pass ✅" >> $GITHUB_STEP_SUMMARY; else echo "__Status__: Fail ❌ " >> $GITHUB_STEP_SUMMARY; fi
 
     - name: Show Stats and Analysis Report
       run: |
